spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/warehouse-management?characterEncoding=utf-8&useSSL=false
    username: root
    password: cbw20020506
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.warehouseManag.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl